// <auto-generated />
using System;
using LaunchCart.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaunchCart.Api.Data.Migrations
{
    [DbContext(typeof(LaunchCartDbContext))]
    [Migration("20260511191554_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaunchCart.Api.Domain.Enquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("LaunchCart.Api.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 11, 19, 15, 54, 463, DateTimeKind.Unspecified).AddTicks(3542), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Handcrafted full-grain leather tote, ideal for everyday use.",
                            ImageUrl = "/images/leather-tote.jpg",
                            IsActive = true,
                            Name = "Leather Tote Bag",
                            Price = 149.99m,
                            Slug = "leather-tote-bag"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 11, 19, 15, 54, 463, DateTimeKind.Unspecified).AddTicks(3563), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Durable waxed-canvas backpack with laptop compartment.",
                            ImageUrl = "/images/canvas-backpack.jpg",
                            IsActive = true,
                            Name = "Canvas Backpack",
                            Price = 89.99m,
                            Slug = "canvas-backpack"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 11, 19, 15, 54, 463, DateTimeKind.Unspecified).AddTicks(3566), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Soft merino wool throw in a classic herringbone weave.",
                            ImageUrl = "/images/wool-throw.jpg",
                            IsActive = true,
                            Name = "Wool Throw Blanket",
                            Price = 119.99m,
                            Slug = "wool-throw-blanket"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 11, 19, 15, 54, 463, DateTimeKind.Unspecified).AddTicks(3568), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Hand-thrown stoneware mug, microwave and dishwasher safe.",
                            ImageUrl = "/images/ceramic-mug.jpg",
                            IsActive = true,
                            Name = "Ceramic Coffee Mug",
                            Price = 34.99m,
                            Slug = "ceramic-coffee-mug"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 5, 11, 19, 15, 54, 463, DateTimeKind.Unspecified).AddTicks(3571), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Set of three hand-poured beeswax candles with cotton wicks.",
                            ImageUrl = "/images/beeswax-candles.jpg",
                            IsActive = true,
                            Name = "Beeswax Candle Set",
                            Price = 44.99m,
                            Slug = "beeswax-candle-set"
                        });
                });

            modelBuilder.Entity("LaunchCart.Api.Domain.Enquiry", b =>
                {
                    b.HasOne("LaunchCart.Api.Domain.Product", "Product")
                        .WithMany("Enquiries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaunchCart.Api.Domain.Product", b =>
                {
                    b.Navigation("Enquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
